model:
  # Core model parameters - Ultra Memory Efficient
  hidden_dim: 128          # Reduced from 256
  num_heads: 4            # Reduced from 8
  num_layers: 4           # Reduced from 6
  dropout: 0.1
  vocab_size: 50000
  max_len: 256           # Reduced further
  beam_size: 2           # Reduced from 4
  vocab_path: "avm/data/processed/vocab.json"
  
  # Memory optimization parameters
  gradient_checkpointing: true
  use_memory_efficient_attention: true
  chunk_size: 64        # Reduced from 128
  
  # Subcomponent configurations - Memory optimized
  components:
    embedding:
      n_symbol_types: 10
      dropout: 0.1
    
    mathematical:
      num_symbol_types: 10
      
    proof_state:
      num_strategies: 5
      
    graph:
      num_layers: 2
      edge_dim: 32
      num_relation_types: 8